[theme]
primaryColor = "#1E90FF"            # Blue for primary elements (e.g., buttons, hover)
backgroundColor = "#000000"         # Black background
secondaryBackgroundColor = "#141414"  # Dark gray for headers/containers
textColor = "#FFFFFF"               # White text
