[theme]
primaryColor="#47594C"            # Greenish color
backgroundColor="#F5F0E1"         # Light khaki
secondaryBackgroundColor="#EBE2CD" # Slightly darker khaki for container backgrounds
textColor="#3B2F2F"               # Warm brown for text
